#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LiftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    RLine,          sensorLineFollower)
#pragma config(Sensor, in3,    LLine,          sensorLineFollower)
#pragma config(Sensor, in4,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl11, StarKnocker,    sensorDigitalOut)
#pragma config(Sensor, dgtl12, Claw,           sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           RFBase,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           LFBase,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           LiftL1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LiftR1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RBBase,        tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port7,           LBBase,        tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port8,           LiftR2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftL23,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LiftR3,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**************************
BUILD DATE: 	11/17/16
AUTHOR: 			JAIVEER SINGH
				V3.1.4
**************************/

//VRC Specific pragmas below
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.h"
//VRC Specific pragmas above

#include "Joystick_Defs.h" 	//Define joystick buttons in more user-friendly terms
#include "Constants.h" 			//All constants used in the entire program
#include "TrueSpeed_Slew.h" //Advanced motor con1*trol for the robot
#include "Base.h"						//All base-control code
#include "Claw.h" 					//All claw-control code
#include "Lift.h" 					//All lift-control code

//Ready for match after reconnect
void pre_auton()
{
	//By slaving motors together, they can never accidentally drive in opposite directions
	slaveMotor(RBBase, RFBase);
	slaveMotor(LBBase, LFBase);
	slaveMotor(LiftR2, LiftR1);
	slaveMotor(LiftR3, LiftR1);
	slaveMotor(LiftL1, LiftR1);
	slaveMotor(LiftL23, LiftR1);
	playTone(750, 10);
	wait1Msec(500);
	SensorValue[Claw] = CLOSED;
}

void driveFd(int time)
{
	motor[RFBase] = 127;
	motor[LFBase] = 127;
	wait1Msec(time);
	motor[RFBase] = 0;
	motor[LFBase] = 0;
}

void driveBk(int time)
{
	motor[RFBase] = -127;
	motor[LFBase] = -127;
	wait1Msec(time);
	motor[RFBase] = 0;
	motor[LFBase] = 0;
}

void turnR(int time)
{
	motor[RFBase] = -127;
	motor[LFBase] = 127;
	wait1Msec(time);
	motor[RFBase] = 0;
	motor[LFBase] = 0;
}

task autonomous()
{
	//Insert name of autonomous function to be run below:
	SensorValue[Claw] = OPEN;
	wait1Msec(1000);
	driveFd(1000);
	wait1Msec(500);
	SensorValue[Claw] = CLOSED;
	wait1Msec(500);
	driveFd(500);
	wait1Msec(1500);
	motor[LiftR1] = 65;
	turnR(700);
	wait1Msec(500);
	motor[LiftR1]= 127;
	driveBk(500);
	wait1Msec(500);
	SensorValue[Claw] = OPEN;
	motor[LiftR1] = 0;
	motor[LiftR1] = -127;
	wait1Msec(500);
	driveBk(350);
	motor[LiftR1] = 0;
	wait1Msec(500);
	driveFd(1250);
	SensorValue[Claw] = CLOSED;
	wait1Msec(500);
	driveBk(500);
	motor[LiftR1] = 127;
	driveBk(750);
	motor[LiftR1] = 0;
	wait1Msec(250);
	SensorValue[Claw] = OPEN;
}

task usercontrol()
{
	//Start all necessary tasks
	//startTask(slewRateController);
	startTask(base);
	startTask(intake);
	startTask(lift);
}
